### ISSUE TITLE
UI bug

### ISSUE THREAD

**Issue by xmha97** [roytam1/UXP#13]
Hello,
I use a third-party theme on Windows XP.

The title bar has a bug:

![Basilisk](https://user-images.githubusercontent.com/23485114/77270964-fd794c00-6cca-11ea-8825-88e902262d10.png)

This theme works fine on all applications:

![image](https://user-images.githubusercontent.com/23485114/77271045-44ffd800-6ccb-11ea-8f89-aa69dd80832e.png)

Thanks

**Comment by roytam1** [comment]
custom windows theme is not supposed to work.
