### ISSUE TITLE
Can't open advanced setting in preferences

### ISSUE THREAD

**Issue by quroe** [roytam1/UXP#14]
## Short description
Nothing happens when I click advanced section in preferences.

## Steps to reproduce
 1. start Serpent.
 2. click `Menu=>Tools=>Preferences=>Advanced` or open `about:preferences#advanced`.

## Expected result
Open Advenced Setting.

## Actual result
Nothing happened.

## Environment
 * Platform (OS): Windows 8.1 x64
 * Version:
basilisk52-g4.5.win64-git-20200411-4662b4f-uxp-552470fb6-xpmod
basilisk52-g4.5.win64-git-20200404-4662b4f-uxp-90a9bc221-xpmod

**Comment by roytam1** [comment]
fixed in rev 9b8c8db3c7c22b8285b52a256835abe5297f9d6d
