### ISSUE TITLE
Moving to a new home

### ISSUE THREAD

**Issue by AroKol78** [roytam1/UXP#16]
Look roytam1 - MoonchildProductions moving to a new home
[ https://forum.palemoon.org/viewtopic.php?f=5&t=25461 ]
[ https://repo.palemoon.org/ ]
[ https://repo.palemoon.org/explore/repos ]

**Comment by roytam1** [comment]
yeah they switched to it today, and my upstream url has been changed. thanks for telling me that.

**Comment by AroKol78** [comment]
`https://repo.palemoon.org/explore/repos` = 404 Not Found - at my place (maybe only temporarily)

the sites are working "MoonchildProductions"
```
https://repo.palemoon.org/MoonchildProductions
https://repo.palemoon.org/MoonchildProductions/UXP
https://repo.palemoon.org/MoonchildProductions/Basilisk
https://repo.palemoon.org/MoonchildProductions/Pale-Moon
```
