### ISSUE TITLE
regression js

### ISSUE THREAD

**Issue by mp3sova** [roytam1/UXP#19]
On the new assembly, lags began to be observed in working with Java scripts, the test confirmed a drop in performance: Kraken JavaScript Benchmark (version 1.1)

basilisk52-g4.7.win64-git-20201205-11839e2-uxp-fd576c427-xpmod
https://i.imgur.com/rWsll9X.jpg

basilisk52-g4.7.win64-git-20201128-11839e2-uxp-a8a397fbc-xpmod
https://i.imgur.com/1jWXE3L.jpg

**Comment by AroKol78** [comment]
**about:config** --> **javascript.options.ion.inlining** switch to true

**Comment by roytam1** [comment]
it is known because javascript inline optimization is off now, you may turn it back on by setting `javascript.options.ion.inlining` in `about:config` to true
