### ISSUE TITLE
Pale Moon 28x nonSSE2 for XP

### ISSUE THREAD

**Issue by Lirk88** [roytam1/UXP#21]
Hi, can you rebuild Pale Moon 28X for XP without SSE2 requirement? There is an Mypal SSE version, based on Pale Moon 28.16 (compiled with MinGW) and it works good, but it would be better to have not restyled Pale Moon version with the same functionality. 

https://github.com/Feodor2/Mypal/issues/126#issuecomment-734425342

**Comment by AroKol78** [comment]
> It works, but much slower, than PaleMoon or MyPal.
>
> because it has full features from UXP, while NewMoon doesn't.

MyPal some functions are missing
Serpent/UXP-ia32 - try the switch https://github.com/roytam1/UXP/issues/19

**Comment by AroKol78** [comment]
> MyPal some functions are missing

new Mypal28.17.0-win32 does not support `https://speed.cloudflare.com/`

I tested the last version basilisk52-win32 in `https://speed.cloudflare.com/` is ok (map display ,test speed)
