### ISSUE TITLE
GMP Widevine to support video DRM

### ISSUE THREAD

**Issue by AroKol78** [roytam1/UXP#26]
is it possible to update and enable , adapt for xp ? 
https://github.com/roytam1/UXP/blob/custom/toolkit/content/gmp-sources/widevinecdm.json it's old and doesn't work 

https://phabricator.services.mozilla.com/D114529
4.10.2209.1-win-ia32
4.10.2209.1-win-x64

**Comment by roytam1** [comment]
> is it possible to update and enable , adapt for xp ?

nope, newer Widevine DLLs use Vista+ APIs.

**Comment by AroKol78** [comment]
thanks for the info
