### ISSUE TITLE
google help page broken

### ISSUE THREAD

**Issue by AroKol78** [roytam1/UXP#27]
Serpent 52-g4.8.win32-git-20210605-e29e57e-uxp-7f6f1c664-xpmod
I tried without additives
I cannot report the problem to google on the website - a month ago it was fine
`https://support.google.com/` `https://support.google.com/accounts/thread/new?hl=pl`
red arrow shows non-working elements
![bug01goole](https://user-images.githubusercontent.com/70756447/122081414-5c127480-cdff-11eb-97c8-2264cd50a8ec.PNG)
![bug03goole](https://user-images.githubusercontent.com/70756447/122081426-603e9200-cdff-11eb-824e-7116392a093c.PNG)
![bug02goole](https://user-images.githubusercontent.com/70756447/122081451-65034600-cdff-11eb-95d0-5a04ec0f01f5.PNG)

**Comment by roytam1** [comment]
because it use a function that exists since firefox 78, which is not implemented in goanna4 engine.
https://caniuse.com/mdn-javascript_builtins_regexp_property_escapes

**Comment by AroKol78** [comment]
it seems the user-agent value (default settings) is being ignored on this page by Google
on the other hand, MC seems to have different priorities
thanks for the clarification anyway
