### ISSUE TITLE
[Feature Request] "privacy.resistFingerprinting.block_mozAddonManager" feature

### ISSUE THREAD

**Issue by quroe** [roytam1/UXP#3]
Firefox57 and higher can allow WebExtensions in AMO by setting.
I want you porting this feature to Serpent.
Simplest method is TorBrowser's bug 24684.
https://gitweb.torproject.org/user/gk/tor-browser.git/commit/?h=bug_21684&id=b2f8585b66dc2856463950c7239015585a8481e3
But user can select (by.pref) may be more better.
Thanks

cf.
1384330 - Don't expose window.navigator.mozAddonManager data when privacy.resistFingerprinting=true
https://bugzilla.mozilla.org/show_bug.cgi?id=1384330
privacy.resistFingerprinting.block_mozAddonManager by laniakea64 · Pull Request #449 · MrAlex94/Waterfox
https://github.com/MrAlex94/Waterfox/pull/449

**Comment by roytam1** [comment]
imported in rev f05d85ff6
