### ISSUE TITLE
Click, js not working

### ISSUE THREAD

**Issue by Stepman123** [roytam1/UXP#6]
On this site, the search results do not work click.
https://www.clashofstats.com/ru/
windows 7 x64;
palemoon-28.7.0a1.win64-git-20190706-a3ed49dde-xpmod
or
palemoon-28.6.0a1.win32-git-20190629-e4b2fa17b-xpmod

**Comment by roytam1** [comment]
> On this site, the search results do not work click.

the site returns 401 to the promises, please contact site owner for the issue.

**Comment by Stepman123** [comment]
It works in Chrome and Maxthon MX5.

**Comment by roytam1** [comment]
> windows 7 x64

please try with official build, if official build still not working on that site, please report to https://github.com/MoonchildProductions/UXP/issues

**Comment by Sa-Ja-Di** [comment]
I guess it is a problem with the user-agent. Testing the Firefox 45.x build and entering an user agent override in the form of native Pale Moon user agent - the results can not be clicked.

If i enter a normal Firefox only user agent, results can be clicked here.

**Comment by roytam1** [comment]
> If i enter a normal Firefox only user agent, results can be clicked here.

so did you tried choosing "Firefox compatibility" in preferences dialog?
